# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  qq: "http://wpa.qq.com/msgrd?v=3&uin=59256790&site=qq&menu=yes"
  weibo: "http://weibo.com/278220017"
  zhihu: "https://www.zhihu.com/people/song-mou-mou-92-99/answers"
  mail: "mailto:59256790@qq.com"
  github: "https://github.com/songyazhao"
  # rss: "#"
  # douban: "#"
  # facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml

# Content
# excerpt_link: 阅读全文
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# 百度统计、谷歌统计
baidu_tongji: true
google_analytics: true

favicon: /img/head_icon.jpg

#你的头像url
avatar: /img/head_icon.jpg

#是否开启分享
share: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: songyazhao

#是否开启云标签
tagcloud: true

#是否开启文章阅读量
leancloud_visitors:
  enable: true
  app_id: jujym3PQqs2CYLtDvL7IzoeG-gzGzoHsz
  app_key: VhdH9bslRJKK6mKVS48uU6Ef


#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  github: https://github.com/songyazhao/songyazhao.github.io
#是否开启“关于我”。
# 不开启——
#aboutme: false
#开启——
# aboutme: 就职于斗米，前端重度极客。

swift_search:
  enable: true
